### ISSUE TITLE
Ignored x_noisy in ControlNet?

### ISSUE THREAD

**Issue by ifeherva** [ali-vilab/AnyDoor#55]
I noticed [here](https://github.com/ali-vilab/AnyDoor/blob/main/cldm/cldm.py#L292) that the noisy sample is practically ignored in the control branch. What is the idea behind getting rid of that condition (instead of let's say adding or concating to the hint)?

**Comment by ifeherva** [comment]
For example: https://github.com/lllyasviel/ControlNet-v1-1-nightly/blob/main/cldm/cldm.py#L296

**Comment by XavierCHEN34** [comment]
Yes, we find that removing the noise would accelerate the convergence, the reason might be that this operation enables stronger controls from the initial steps.

**Comment by ifeherva** [comment]
Thanks a lot, that makes sense.
